### ISSUE TITLE
Index input to texcoord use case

### ISSUE THREAD

**Issue by cagucor** [dpisani/gltf-builder#7]
I have seen the documentation, but I do not understand what this index is used for when constructing the texture coordinates. Could you please give an example of a use case?

**Comment by dpisani** [comment]
Hi @cagucor. Could you elaborate more on what in particular you don't understand, or perhaps describe what you're trying to achieve?

It's not necessary to use indices in order to construct texture coordinates for vertices in your primitives. However they can be used if you want to reduce the memory footprint of your primitives by re-using existing vertices.

**Comment by cagucor** [comment]
I have two sets of data: the texture coordinates and their respective indices similar to position and index values. I was wondering if the index input could be used to specify a corresponding order to a list of texture positions.

**Comment by dpisani** [comment]
I see!

You'll need to provide the data in the right order for both `position` and `texcoord`, since the order in the array is used when defining the vertices in your primitive.

To illustrate, consider this sample:

```
new Primitive()
          .position(
            buildVec3Accessor([[0, 0, 0], [1, 0, 0], [0, 1, 0]])
          )
          .texcoord(buildVec2Accessor([[0, 0], [1, 0], [0, 1]]))
```


In this example here, we have 3 vertices:

- position: (0, 0, 0), texcoord: (0, 0)
- position: (1, 0, 0), texcoord: (1, 0) 
- position: (0, 1, 0), texcoord: (0, 1) 

If you have two separate data sets, you'll have to match them up yourself before adding them to the primitive. Indices only have a purpose if you want to re-use entire _vertices_. You can't use indices to re-use individual position or texcoord values.

Hope that helps!
